language: python
python:
    - "2.7"
# command to install dependencies
install: "pip install -r requirements/ci.txt --use-mirrors"
# script to run before running tests
before_script:
    - cd email-service
    - export EMAIL_SERVICE_SETTINGS="config/testing.py"
    - export PYTHONPATH=.:$PYTHONPATH
# command to run tests
script:
    - nosetests --with-coverage --cover-package=. test
# post success scripts to run
after_success:
    - coveralls
# notification settings
notifications:
    email:
        recipients:
            - tapan.pandita@gmail.com
        on_success: change
        on_failure: always
# whitelist
branches:
    only:
        - master
        - develop
